# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WebCam.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# from Content.img.QRC import resourcesAutonoma


class Ui_WebCam(object):
    def setupUi(self, WebCam):
            
        # Desabilitando barra de titulo
        WebCam.setWindowFlags(QtCore.Qt.FramelessWindowHint)     
        
        WebCam.setObjectName("WebCam")
        WebCam.resize(750, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WebCam.sizePolicy().hasHeightForWidth())
        WebCam.setSizePolicy(sizePolicy)
        WebCam.setMinimumSize(QtCore.QSize(750, 750))
        WebCam.setMaximumSize(QtCore.QSize(750, 750))
        self.verticalLayout = QtWidgets.QVBoxLayout(WebCam)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridNome = QtWidgets.QHBoxLayout()
        self.gridNome.setSpacing(0)
        self.gridNome.setObjectName("gridNome")
        self.label = QtWidgets.QLabel(WebCam)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"color: #192E4D;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridNome.addWidget(self.label)
        self.lblNome = QtWidgets.QLabel(WebCam)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lblNome.setFont(font)
        self.lblNome.setStyleSheet("QLabel{\n"
"color: #192E4D;\n"
"}")
        self.lblNome.setObjectName("lblNome")
        self.gridNome.addWidget(self.lblNome)
        self.verticalLayout.addLayout(self.gridNome)
        self.lblMensagem = QtWidgets.QLabel(WebCam)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lblMensagem.setFont(font)
        self.lblMensagem.setStyleSheet("QLabel{\n"
"color: #192E4D;\n"
"}")
        self.lblMensagem.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMensagem.setObjectName("lblMensagem")
        self.verticalLayout.addWidget(self.lblMensagem)
        self.divWebCam = QtWidgets.QLabel(WebCam)
        self.divWebCam.setText("")
        self.divWebCam.setScaledContents(True)
        self.divWebCam.setObjectName("divWebCam")
        self.verticalLayout.addWidget(self.divWebCam)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 10)
        
        self.label.hide()
        self.lblNome.hide()

        self.retranslateUi(WebCam)
        QtCore.QMetaObject.connectSlotsByName(WebCam)

    def retranslateUi(self, WebCam):
        _translate = QtCore.QCoreApplication.translate
        WebCam.setWindowTitle(_translate("WebCam", "Reconhecimento"))
        self.label.setText(_translate("WebCam", "Olá, "))
        self.lblNome.setText(_translate("WebCam", "USUARIO"))
        self.lblMensagem.setText(_translate("WebCam", "Validando sua identidade\n"
"Olhe e aguarde!"))
